language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.1

otp_release:
  - 19.3
  - 20.1

matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.1

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix compile
  - mix test
  - mix dialyzer
  - mix credo --strict

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

after_success:
  - MIX_ENV=test mix coveralls.travis
