language: elixir
elixir:
  - 1.3.4
  - 1.4.2
otp_release: 19.3
script:
  - mix deps.get
  - mix compile
  - mix test
  - mix dialyzer
  - mix credo --strict
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - .dialyzer
