language: elixir
elixir:
  - 1.3.4
  - 1.4.5
otp_release:
  - 19.3
  - 20.0
script:
  - mix deps.get
  - mix compile
  - mix test
  - mix dialyzer
  - mix credo --strict
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
