-file("c:/Program Files/erl9.0/lib/parsetools-2.1.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(toml_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/toml_lexer.xrl", 79).

-export([tokenize/1]).

%% @doc Lexer entry point.

-spec tokenize(string() | binary() | iolist()) ->
  {ok, [term()], integer()} | {error, term(), integer()}.

tokenize(String) ->
  string(unicode:characters_to_list([String, $\n])).

to_integer("+" ++ String) ->
  to_integer(String);
to_integer("-" ++ String) ->
  -to_integer(String);
to_integer(String) ->
  list_to_integer([C || C <- String, C /= $_]).

to_float(String) ->
  StripUnderscore = [C || C <- String, C /= $_],
  case string:chr(StripUnderscore, $.) of
    0 ->
      % fix the float for Erlang's parsing function by inserting the missing
      % fraction part just before "e" marker
      % NOTE: we're here because either "." or "[eE]" was found in the number,
      % and we know the "." is missing
      [A, B] = string:tokens(StripUnderscore, "eE"),
      list_to_float(A ++ ".0e" ++ B);
    _ ->
      list_to_float(StripUnderscore)
  end.

datetime_tz(String) ->
  StrLen = length(String),
  case lists:last(String) of
    $Z ->
      Timezone = "Z",
      {local_datetime(string:substr(String, 1, StrLen - 1)), Timezone};
    _ ->
      Timezone = string:substr(String, 1 + StrLen - 6, 6),
      {local_datetime(string:substr(String, 1, StrLen - 6)), Timezone}
  end.

local_datetime(String) ->
  [Date, Time] = string:tokens(String, "T"),
  {local_date(Date), local_time(Time)}.

local_date(String) ->
  [Y, M, D] = string:tokens(String, "-"),
  {list_to_integer(Y), list_to_integer(M), list_to_integer(D)}.

local_time(String) ->
  [HH, MM, SS] = string:tokens(String, ":"),
  case string:tokens(SS, ".") of
    [_] ->
      {list_to_integer(HH), list_to_integer(MM), list_to_integer(SS)};
    [S, Frac] ->
      {{list_to_integer(HH), list_to_integer(MM), list_to_integer(S)}, Frac}
  end.

literal_string(String) ->
  string:substr(String, 2, length(String) - 2).

literal_string_ml(String) ->
  case string:substr(String, 4, length(String) - 6) of
    "\r\n" ++ Result -> Result;
    "\n" ++ Result -> Result;
    Result -> Result
  end.

basic_string(String) ->
  escape(string:substr(String, 2, length(String) - 2)).

basic_string_ml(String) ->
  case string:substr(String, 4, length(String) - 6) of
    "\r\n" ++ Result -> escape(Result);
    "\n" ++ Result -> escape(Result);
    Result -> escape(Result)
  end.

escape("") -> "";
escape("\\b"  ++ Rest) -> [$\b | escape(Rest)];
escape("\\t"  ++ Rest) -> [$\t | escape(Rest)];
escape("\\n"  ++ Rest) -> [$\n | escape(Rest)];
escape("\\f"  ++ Rest) -> [$\f | escape(Rest)];
escape("\\r"  ++ Rest) -> [$\r | escape(Rest)];
escape("\\\"" ++ Rest) -> [$\" | escape(Rest)];
escape("\\\\" ++ Rest) -> [$\\ | escape(Rest)];
escape("\\u"  ++ [C1, C2, C3, C4 | Rest]) ->
  [u([C4, C3, C2, C1]) | escape(Rest)];
escape("\\U"  ++ [C1, C2, C3, C4, C5, C6, C7, C8 | Rest]) ->
  [u([C8, C7, C6, C5, C4, C3, C2, C1]) | escape(Rest)];
escape("\\" ++ Rest) ->
  escape(skip_spaces(Rest));
escape([C | Rest]) ->
  [C | escape(Rest)].

skip_spaces(" " ++ Rest) -> skip_spaces(Rest);
skip_spaces("\t" ++ Rest) -> skip_spaces(Rest);
skip_spaces("\n" ++ Rest) -> skip_spaces(Rest);
skip_spaces("\r\n" ++ Rest) -> skip_spaces(Rest);
skip_spaces(String) -> String.

u([]) -> 0;
u([C | Rest]) when C >= $0 andalso C =< $9 ->      (C - $0) + 16 * u(Rest);
u([C | Rest]) when C >= $A andalso C =< $F -> (10 + C - $A) + 16 * u(Rest);
u([C | Rest]) when C >= $a andalso C =< $f -> (10 + C - $a) + 16 * u(Rest).

-file("c:/Program Files/erl9.0/lib/parsetools-2.1.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/toml_lexer.erl", 410).
yystate() -> 73.

yystate(136, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(136, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,136};
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(135, Ics, Line, Tlen+1, 26, Tlen);
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(135, Ics, Line, Tlen+1, 26, Tlen);
yystate(135, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,135};
yystate(134, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 51 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(134, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,134};
yystate(133, [101|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 19, Tlen);
yystate(133, [69|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 19, Tlen);
yystate(133, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 19, Tlen);
yystate(133, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,133};
yystate(132, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, [48|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(132, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,132};
yystate(131, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 18, Tlen);
yystate(131, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(131, Ics, Line, Tlen+1, 18, Tlen);
yystate(131, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,131};
yystate(130, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(130, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,130};
yystate(129, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [84|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(129, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,129};
yystate(128, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line+1, Tlen+1, Action, Alen);
yystate(128, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,128};
yystate(127, [108|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(127, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,127};
yystate(126, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(126, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,126};
yystate(125, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(125, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 20, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(125, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(125, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,125};
yystate(124, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(124, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(124, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,124};
yystate(123, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(122, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(122, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(122, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(122, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,122};
yystate(121, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(121, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,121};
yystate(120, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [49|Ics], Line, Tlen, _, _) ->
    yystate(106, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [48|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 50, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(120, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,120};
yystate(119, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(119, [45|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 20, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(119, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,119};
yystate(118, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(118, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(118, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(118, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,118};
yystate(117, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(117, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,117};
yystate(116, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(115, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(115, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(115, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(115, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,115};
yystate(114, [114|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(114, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,114};
yystate(113, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(113, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(113, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(112, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,112};
yystate(111, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(110, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(110, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,110};
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(107, [90|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 11, Tlen);
yystate(107, [46|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 11, Tlen);
yystate(107, [45|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 11, Tlen);
yystate(107, [43|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 11, Tlen);
yystate(107, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,107};
yystate(106, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 50 ->
    yystate(42, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 51, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,106};
yystate(105, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(104, [117|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,104};
yystate(103, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(103, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,102};
yystate(101, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,101};
yystate(100, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(99, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(99, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(119, Ics, Line, Tlen+1, 20, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(99, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,99};
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,98};
yystate(97, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(97, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(97, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,96};
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(93, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,93};
yystate(92, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(118, Ics, Line, Tlen+1, Action, Alen);
yystate(92, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(118, Ics, Line, Tlen+1, Action, Alen);
yystate(92, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(118, Ics, Line, Tlen+1, Action, Alen);
yystate(92, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,92};
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,90};
yystate(89, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [58|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,88};
yystate(87, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(86, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 20, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,86};
yystate(85, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(83, [97|Ics], Line, Tlen, _, _) ->
    yystate(127, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,83};
yystate(82, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [48|Ics], Line, Tlen, _, _) ->
    yystate(129, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [49|Ics], Line, Tlen, _, _) ->
    yystate(129, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 50, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,81};
yystate(80, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, [48|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(129, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,78};
yystate(77, [101|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 19, Tlen);
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 19, Tlen);
yystate(77, [69|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 19, Tlen);
yystate(77, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 19, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 19, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,77};
yystate(76, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(122, Ics, Line, Tlen+1, Action, Alen);
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(122, Ics, Line, Tlen+1, Action, Alen);
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(122, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(116, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(130, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(135, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(128, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line+1, Tlen+1, Action, Alen);
yystate(73, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 51, C =< 57 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 101 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 115 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [115|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,71};
yystate(70, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,68};
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [46|Ics], Line, Tlen, _, _) ->
    yystate(121, Ics, Line, Tlen+1, 13, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,66};
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [50|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [48|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [49|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 51, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,65};
yystate(64, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [45|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,64};
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(126, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,61};
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, [48|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,60};
yystate(59, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,59};
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, [58|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,58};
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(57, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,57};
yystate(56, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 51 ->
    yystate(88, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 52, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,52};
yystate(51, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(45, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, 20, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,45};
yystate(44, [101|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,44};
yystate(43, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(42, [45|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 20, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,42};
yystate(41, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(40, [101|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 18, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 18, Tlen);
yystate(40, [69|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 18, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 18, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,40};
yystate(39, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(39, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [48|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [45|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [43|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,37};
yystate(36, [34|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 21, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, [58|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(99, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,35};
yystate(34, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,33};
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, 18, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,31};
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(30, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(28, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,28};
yystate(27, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(25, [54|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,22};
yystate(21, [39|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,21};
yystate(20, [54|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,19};
yystate(18, [93|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, [91|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, [32|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, [9|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [51|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [49|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [50|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [48|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 52, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,17};
yystate(16, [90|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 11, Tlen);
yystate(16, [45|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 11, Tlen);
yystate(16, [43|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 11, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 11, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,16};
yystate(15, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(14, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(129, Ics, Line, Tlen+1, 20, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,14};
yystate(13, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [48|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,8};
yystate(7, [101|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,7};
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 51 ->
    yystate(58, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 52, C =< 57 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 20, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,5};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [69|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [45|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(64, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,4};
yystate(3, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(1, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, _, _, _) ->
    yyaction_25();
yyaction(26, _, _, _) ->
    yyaction_26();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/toml_lexer.xrl", 42).
yyaction_0(TokenLine) ->
     { token, { space, TokenLine }, "[" } .

-compile({inline,yyaction_1/1}).
-file("src/toml_lexer.xrl", 43).
yyaction_1(TokenLine) ->
     { token, { space, TokenLine }, "]" } .

-compile({inline,yyaction_2/1}).
-file("src/toml_lexer.xrl", 44).
yyaction_2(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("src/toml_lexer.xrl", 45).
yyaction_3(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("src/toml_lexer.xrl", 46).
yyaction_4(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/toml_lexer.xrl", 47).
yyaction_5(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/toml_lexer.xrl", 48).
yyaction_6(TokenLine) ->
     { token, { '.', TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/toml_lexer.xrl", 49).
yyaction_7(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/toml_lexer.xrl", 50).
yyaction_8(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/toml_lexer.xrl", 51).
yyaction_9(TokenLine) ->
     { token, { nl, TokenLine } } .

-compile({inline,yyaction_10/2}).
-file("src/toml_lexer.xrl", 53).
yyaction_10(TokenChars, TokenLine) ->
     { token, { datetime_tz, TokenLine, datetime_tz (TokenChars) } } .

-compile({inline,yyaction_11/2}).
-file("src/toml_lexer.xrl", 54).
yyaction_11(TokenChars, TokenLine) ->
     { token, { local_datetime, TokenLine, local_datetime (TokenChars) } } .

-compile({inline,yyaction_12/2}).
-file("src/toml_lexer.xrl", 56).
yyaction_12(TokenChars, TokenLine) ->
     { token, { local_date, TokenLine, { TokenChars, local_date (TokenChars) } } } .

-compile({inline,yyaction_13/2}).
-file("src/toml_lexer.xrl", 57).
yyaction_13(TokenChars, TokenLine) ->
     { token, { local_time, TokenLine, local_time (TokenChars) } } .

-compile({inline,yyaction_14/1}).
-file("src/toml_lexer.xrl", 60).
yyaction_14(TokenLine) ->
     { token, { bool, TokenLine, true } } .

-compile({inline,yyaction_15/1}).
-file("src/toml_lexer.xrl", 61).
yyaction_15(TokenLine) ->
     { token, { bool, TokenLine, false } } .

-compile({inline,yyaction_16/2}).
-file("src/toml_lexer.xrl", 63).
yyaction_16(TokenChars, TokenLine) ->
     { token, { key_float, TokenLine, { TokenChars, to_float (TokenChars) } } } .

-compile({inline,yyaction_17/2}).
-file("src/toml_lexer.xrl", 64).
yyaction_17(TokenChars, TokenLine) ->
     { token, { key_integer, TokenLine, { TokenChars, to_integer (TokenChars) } } } .

-compile({inline,yyaction_18/2}).
-file("src/toml_lexer.xrl", 65).
yyaction_18(TokenChars, TokenLine) ->
     { token, { float, TokenLine, to_float (TokenChars) } } .

-compile({inline,yyaction_19/2}).
-file("src/toml_lexer.xrl", 66).
yyaction_19(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, to_integer (TokenChars) } } .

-compile({inline,yyaction_20/2}).
-file("src/toml_lexer.xrl", 67).
yyaction_20(TokenChars, TokenLine) ->
     { token, { bare_key, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/2}).
-file("src/toml_lexer.xrl", 69).
yyaction_21(TokenChars, TokenLine) ->
     { token, { basic_string, TokenLine, basic_string (TokenChars) } } .

-compile({inline,yyaction_22/2}).
-file("src/toml_lexer.xrl", 70).
yyaction_22(TokenChars, TokenLine) ->
     { token, { literal_string, TokenLine, literal_string (TokenChars) } } .

-compile({inline,yyaction_23/2}).
-file("src/toml_lexer.xrl", 71).
yyaction_23(TokenChars, TokenLine) ->
     { token, { basic_string_ml, TokenLine, basic_string_ml (TokenChars) } } .

-compile({inline,yyaction_24/2}).
-file("src/toml_lexer.xrl", 72).
yyaction_24(TokenChars, TokenLine) ->
     { token, { literal_string_ml, TokenLine, literal_string_ml (TokenChars) } } .

-compile({inline,yyaction_25/0}).
-file("src/toml_lexer.xrl", 74).
yyaction_25() ->
     skip_token .

-compile({inline,yyaction_26/0}).
-file("src/toml_lexer.xrl", 75).
yyaction_26() ->
     skip_token .

-file("c:/Program Files/erl9.0/lib/parsetools-2.1.5/include/leexinc.hrl", 309).
